/**
 * AGriVyn - Mock Database & Static Data
 * High-fidelity simulated data for Smart India Hackathon Prototype
 */

const AGRI_DATA = {
  // Available Crops for trading & scan
  crops: [
    { id: 'wheat', name: 'Wheat (Gehun - Sharbati)', unit: 'Quintal', defaultPrice: 2550, harvestDate: '2026-09-05' },
    { id: 'onion', name: 'Onion (Pyaz - Nashik Red)', unit: 'Quintal', defaultPrice: 1950, harvestDate: '2026-09-12' },
    { id: 'mustard', name: 'Mustard (Sarson - Pusa Bold)', unit: 'Quintal', defaultPrice: 5400, harvestDate: '2026-10-01' },
    { id: 'potato', name: 'Potato (Aloo - Kufri Jyoti)', unit: 'Quintal', defaultPrice: 1450, harvestDate: '2026-09-20' },
    { id: 'paddy', name: 'Paddy (Dhan - Basmati 1121)', unit: 'Quintal', defaultPrice: 3850, harvestDate: '2026-10-15' }
  ],

  // Market comparison prices for Wheat in Meerut Region
  marketPrices: {
    Wheat: [
      { name: 'Buyer B (Sharma Agro)', type: 'Private Wholesaler', distance: 15, quotedPrice: 2550, transportPerQtl: 100, isRecommended: true },
      { name: 'Mandi C (Muzaffarnagar APMC)', type: 'Govt APMC Yard', distance: 52, quotedPrice: 2500, transportPerQtl: 180, isRecommended: false },
      { name: 'Buyer D (AgriBridge Trader)', type: 'Institutional Trader', distance: 31, quotedPrice: 2450, transportPerQtl: 130, isRecommended: false },
      { name: 'Mandi A (Hapur APMC)', type: 'Local Mandi', distance: 38, quotedPrice: 2400, transportPerQtl: 145, isRecommended: false }
    ],
    Onion: [
      { name: 'Buyer B (Sharma Agro)', type: 'Private Wholesaler', distance: 15, quotedPrice: 1950, transportPerQtl: 90, isRecommended: true },
      { name: 'Buyer C (Kisan Processing)', type: 'Food Processor', distance: 40, quotedPrice: 1920, transportPerQtl: 150, isRecommended: false },
      { name: 'Mandi A (Hapur APMC)', type: 'Local Mandi', distance: 38, quotedPrice: 1850, transportPerQtl: 140, isRecommended: false }
    ],
    Mustard: [
      { name: 'Buyer B (Sharma Agro)', type: 'Private Wholesaler', distance: 15, quotedPrice: 5450, transportPerQtl: 110, isRecommended: true },
      { name: 'Mandi C (Muzaffarnagar APMC)', type: 'Govt APMC Yard', distance: 52, quotedPrice: 5350, transportPerQtl: 190, isRecommended: false }
    ]
  },

  // 7-day trend data
  trends: {
    Wheat: [
      { date: '24 Aug', price: 2430 },
      { date: '25 Aug', price: 2445 },
      { date: '26 Aug', price: 2460 },
      { date: '27 Aug', price: 2455 },
      { date: '28 Aug', price: 2490 },
      { date: '29 Aug', price: 2520 },
      { date: 'Today', price: 2550 }
    ]
  },

  // AI Crop Health Knowledge Base & Pre-trained Inference Simulation
  diseaseDatabase: {
    onion: {
      crop: 'Onion (Pyaz)',
      condition: 'Early Fungal Infection',
      pathogen: 'Alternaria porri (Purple Blotch)',
      confidence: 94,
      severity: 'Medium',
      affectedArea: 'Leaf surface (12%)',
      recommendation: 'Early intervention recommended. Monitor affected leaves and follow appropriate crop-management guidance. Apply Copper Oxychloride (2.5g/L) or Trichoderma viride. Avoid overhead irrigation.',
      organicControl: 'Spray Neem Oil formulation (3ml/L) or Trichoderma harzianum bio-fungicide.',
      chemicalControl: 'Mancozeb 75% WP @ 2.5g/L or Hexaconazole 5% SC @ 1ml/L water.',
      marketImpact: 'Bulb quality intact. Harvest within 10 days for Grade A pricing.',
      visualIcon: '🧅',
      badgeClass: 'text-red-600'
    },
    wheat: {
      crop: 'Wheat (Gehun)',
      condition: 'Yellow Rust (Early Stage)',
      pathogen: 'Puccinia striiformis',
      confidence: 96,
      severity: 'Low - Contained',
      affectedArea: 'Lower canopy (5%)',
      recommendation: 'Spot treatment with Propiconazole (1ml/L). Isolate affected perimeter. Overall grain quality remains Grade A.',
      organicControl: 'Foliar spray of fermented butter milk + asafoetida solution or bio-fungicide.',
      chemicalControl: 'Tilt 25 EC (Propiconazole) @ 1ml per litre of water.',
      marketImpact: 'Foliar localized only. Grains fully plump; qualified for premium wholesale bids.',
      visualIcon: '🌾',
      badgeClass: 'text-amber-600'
    },
    healthy: {
      crop: 'Wheat (Sharbati)',
      condition: 'Healthy - No Disease',
      pathogen: 'Optimal Physiological Health',
      confidence: 99,
      severity: 'None (Healthy ✓)',
      affectedArea: '0% Affected',
      recommendation: 'Crop is in optimal physiological health. Qualified for Grade A Premium pricing across bulk wholesale markets.',
      organicControl: 'Continue standard bio-fertilizer and balanced irrigation scheduling.',
      chemicalControl: 'No chemical intervention needed.',
      marketImpact: 'Certified Grade A Premium Lot. Recommended for direct institutional procurement.',
      visualIcon: '🌿',
      badgeClass: 'text-emerald-600'
    }
  },

  // Verified Buyer Marketplace
  buyers: [
    {
      id: 'buyer-b',
      name: 'Buyer B (Sharma Agro Enterprises)',
      type: 'Wholesaler',
      rating: 4.8,
      verified: true,
      requiredQty: '50 Quintal',
      offeredPrice: 2600,
      distance: 25,
      location: 'Meerut Industrial Area, UP',
      crops: ['Wheat', 'Mustard', 'Paddy'],
      paymentTerms: 'Online / Bank Transfer (DBT)',
      about: 'Registered agricultural wholesaler supplying NCR retail chains and grain elevators.'
    },
    {
      id: 'buyer-c',
      name: 'Buyer C (Kisan Agro Processing)',
      type: 'Food Processor',
      rating: 4.6,
      verified: true,
      requiredQty: '30 Quintal',
      offeredPrice: 2480,
      distance: 40,
      location: 'Modinagar Industrial Zone, UP',
      crops: ['Wheat', 'Onion'],
      paymentTerms: 'Direct Bank Transfer / Escrow',
      about: 'Certified grain processing unit manufacturing packaged whole wheat flour.'
    },
    {
      id: 'buyer-d',
      name: 'Buyer D (AgriBridge Trader)',
      type: 'Trader',
      rating: 4.4,
      verified: true,
      requiredQty: '20 Quintal',
      offeredPrice: 2450,
      distance: 18,
      location: 'Hapur Mandi Yard, UP',
      crops: ['Wheat', 'Mustard'],
      paymentTerms: 'Instant UPI / NEFT',
      about: 'Licensed APMC commission merchant facilitating direct procurement.'
    }
  ],

  // Weather Data for Meerut, UP
  weather: {
    location: 'Meerut, Uttar Pradesh',
    today: {
      temp: '29°C',
      condition: 'Partly Cloudy',
      icon: '⛅',
      rainProb: '40%',
      humidity: '72%',
      wind: '12 km/h NW'
    },
    alert: {
      title: 'FARM ALERT & ADVISORY',
      message: 'Rain probability is increasing over the next few days (65% expected on Wednesday).',
      actions: [
        'Consider checking crop readiness and transportation availability before dispatch.',
        'Ensure harvested grains in open yards are covered with tarpaulin sheets.'
      ]
    },
    forecast: [
      { day: 'Today', icon: '⛅', cond: 'Partly Cloudy', rain: '40%', high: '29°', low: '22°' },
      { day: 'Tue', icon: '🌦️', cond: 'Scattered Showers', rain: '55%', high: '28°', low: '21°' },
      { day: 'Wed', icon: '🌧️', cond: 'Moderate Rain', rain: '75%', high: '26°', low: '20°', highlight: true },
      { day: 'Thu', icon: '⛅', cond: 'Clearing', rain: '20%', high: '30°', low: '21°' },
      { day: 'Fri', icon: '☀️', cond: 'Sunny', rain: '10%', high: '32°', low: '22°' }
    ]
  },

  // Initial Direct Negotiation Chat Messages
  initialChat: [
    { sender: 'farmer', name: 'Ramesh Kumar', text: 'Namaste Sharma ji. Maine 10 Quintal Sharbati Gehun list kiya hai (Grade A verified, 94% AI Healthy).', time: '10:30 AM' },
    { sender: 'buyer', name: 'Sharma Agro', text: 'Namaste Ramesh ji. Kya aap ₹2,550/Qtl me Meerut Industrial warehouse par deliver kar sakte hain?', time: '10:32 AM' },
    { sender: 'farmer', name: 'Ramesh Kumar', text: 'Haan ji, mini-truck se kal subah 10 baje bhej dunga. Total amount ₹25,500 ban raha hai.', time: '10:35 AM' }
  ]
};


const AGRI_TRANSLATIONS = {
  "Smart decisions from farm to market.": "खेत से बाज़ार तक सही और लाभदायक फैसले।",
  "AI-Powered Farm-to-Market Intelligence Platform": "एआई-संचालित कृषि बाज़ार एवं मूल्य खोज मंच",
  "Explore Farmer Mode": "किसान मोड देखें",
  "Explore Buyer Portal": "खरीदार पोर्टल देखें",
  "Direct Market Linkages & Price Discovery": "सीधा बाज़ार संपर्क और सटीक मूल्य खोज",
  "Integrated AI Crop Health Diagnosis": "एआई द्वारा फसल रोग एवं गुणवत्ता जांच",
  "Direct Farmer ⇄ Buyer Deal Negotiation": "किसान और खरीदार के बीच सीधा सौदा व चैट",
  "Farmer Login (Ramesh - Meerut)": "किसान लॉगिन (रमेश - मेरठ)",
  "Buyer Login (Sharma Agro Wholesaler)": "खरीदार लॉगिन (शर्मा एग्रो ट्रेडर्स)",
  "Hello, Ramesh 👋": "नमस्ते, रमेश 👋",
  "Meerut, Uttar Pradesh": "मेरठ, उत्तर प्रदेश",
  "Active Farmer • Verified Profile ✓": "सक्रिय किसान • सत्यापित प्रोफ़ाइल ✓",
  "TODAY'S BEST SELLING OPPORTUNITY": "आज का सबसे बेहतरीन बिक्री अवसर",
  "Wheat (Gehun - Sharbati)": "गेहूं (शरबती किस्म)",
  "Best Buyer: Mandi/Bulk Buyer B (Sharma Agro)": "सर्वश्रेष्ठ खरीदार: थोक खरीदार बी (शर्मा एग्रो)",
  "Expected Net Price:": "हाथ में शुद्ध भाव:",
  "(After ₹100 estimated transport)": "(₹100 अनुमानित भाड़ा काटने के बाद)",
  "View Recommendation": "सिफारिश देखें",
  "Quick Actions": "त्वरित सेवाएं",
  "My Crops": "मेरी फसलें",
  "List & Manage": "जोड़ें व देखें",
  "Market Prices": "मंडी भाव",
  "Price Discovery": "सटीक दाम",
  "Find Buyers": "खरीदार खोजें",
  "Direct Linkage": "सीधा संपर्क",
  "AI Crop Scan": "एआई फसल जांच",
  "Pest & Health": "रोग व स्वास्थ्य",
  "Weather": "मौसम पूर्वानुमान",
  "Agro Forecast": "7-दिवसीय सलाह",
  "My Orders": "मेरे ऑर्डर",
  "1 Active Offer": "1 सक्रिय सौदा",
  "AI CROP HEALTH": "एआई फसल स्वास्थ्य",
  "Check your crop for diseases & pests before taking to market": "मंडी ले जाने से पहले फसल की बीमारी व गुणवत्ता की जांच करें",
  "Last Scan: Wheat (Healthy ✓)": "अंतिम जांच: गेहूं (स्वस्थ ✓)",
  "Scan Crop": "फसल जांचें",
  "SMART SELLING RECOMMENDATION": "एआई स्मार्ट बिक्री सिफारिश",
  "Best Option For You": "आपके लिए सर्वश्रेष्ठ विकल्प",
  "Why this buyer?": "यह खरीदार क्यों चुनें?",
  "Higher effective price": "अधिक शुद्ध मुनाफा",
  "Good quantity match": "मात्रा की पूरी मांग",
  "Nearby (15 km away)": "नजदीक (15 किमी दूरी)",
  "Verified Buyer ✓": "सत्यापित खरीदार ✓",
  "Net In-Hand: ₹2,450/Qtl": "शुद्ध हाथ में: ₹2,450/क्विंटल",
  "Chat & Negotiate": "बातचीत व मोलभाव",
  "Send Direct Offer": "सीधा ऑफर भेजें",
  "Agro-Weather Advisory": "मौसम कृषि परामर्श",
  "AI Crop Health Scanner": "एआई फसल रोग व स्वास्थ्य जांच",
  "Upload Crop Image for Disease & Pest Scan": "बीमारी व कीट जांच के लिए पत्ते की फोटो लें",
  "Select Sample Demo Image or Upload Custom:": "डेमो सैंपल चुनें या फोटो खींचें:",
  "Onion (Pyaz)": "प्याज (Pyaz)",
  "Wheat (Gehun)": "गेहूं (Gehun)",
  "Healthy Wheat": "स्वस्थ गेहूं",
  "Run AI Crop Diagnostic Scan": "एआई फसल जांच शुरू करें",
  "AI ANALYSIS RESULT": "एआई जांच परिणाम",
  "Crop:": "फसल:",
  "Detected Condition:": "पहचानी गई स्थिति:",
  "Severity Level:": "गंभीरता स्तर:",
  "Affected Area:": "प्रभावित क्षेत्र:",
  "Farmer Recommendation:": "किसान के लिए कृषि सलाह:",
  "View Detailed Report": "विस्तृत रिपोर्ट देखें",
  "Find Suitable Buyers": "उपयुक्त खरीदार खोजें",
  "Mandi Price Discovery": "मंडी मूल्य खोज",
  "Filter by Crop:": "फसल चुनें:",
  "Market / Buyer Comparison": "मंडी व खरीदार भाव तुलना",
  "Quoted Price": "बोली का भाव",
  "Distance": "दूरी",
  "Est. Transport": "अनुमानित भाड़ा",
  "Net In-Hand": "शुद्ध हाथ में",
  "Action": "कार्रवाई",
  "Sell Here": "यहाँ बेचें",
  "7-Day Price Trend & AI Market Insight": "7-दिवसीय मूल्य रुझान व एआई बाज़ार समीक्षा",
  "My Orders & Fulfilment": "मेरे ऑर्डर व डिलीवरी ट्रैकिंग",
  "Offer Sent": "ऑफर भेजा",
  "Accepted by Buyer": "खरीदार द्वारा स्वीकृत",
  "In Transit": "रास्ते में",
  "Completed & Paid": "पूर्ण व भुगतान प्राप्त",
  "Advance Status (Judge Demo)": "स्टेटस आगे बढ़ाएं (डेमो)",
  "Chat Buyer": "खरीदार से चैट",
  "Buyer Portal": "थोक खरीदार पोर्टल",
  "Active Requirements": "सक्रिय मांग",
  "Pending Offers": "प्राप्त ऑफर",
  "Post New Crop Requirement": "नई फसल की मांग पोस्ट करें",
  "AI MATCH FOUND": "एआई सर्वश्रेष्ठ मिलान",
  "AVAILABLE FARMER PRODUCE": "उपलब्ध किसान उत्पाद",
  "View Produce Details": "फसल विवरण देखें",
  "Chat with Ramesh": "रमेश से चैट करें",
  "Lock Purchase Order": "सौदा पक्का करें",
  "Lock Deal Offer": "ऑफर लॉक करें",
  "Direct Negotiation Chat": "सीधी बातचीत व मोलभाव",
  "Deal confirmed! Order dispatching tomorrow.": "सौदा पक्का! कल सुबह माल dispatch होगा।",
  "Need more quantity": "और मात्रा उपलब्ध है क्या?",
  "Instant DBT Payment on delivery": "डिलीवरी पर डायरेक्ट DBT भुगतान",
  "Type direct message to negotiate...": "मोलभाव के लिए संदेश लिखें...",
  "Send": "भेजें",
  "Farmer Mode": "किसान मोड",
  "Direct Chat": "सीधी चैट",
  "Home": "होम",
  "Crops": "फसलें",
  "Buyers": "खरीदार",
  "Orders": "ऑर्डर",
  "Profile": "प्रोफ़ाइल",
  "Dashboard": "डैशबोर्ड",
  "Requirements": "मांग",
  "Chats": "चैट"
};
const AGRI_REV_TRANSLATIONS = {
  "खेत से बाज़ार तक सही और लाभदायक फैसले।": "Smart decisions from farm to market.",
  "एआई-संचालित कृषि बाज़ार एवं मूल्य खोज मंच": "AI-Powered Farm-to-Market Intelligence Platform",
  "किसान मोड देखें": "Explore Farmer Mode",
  "खरीदार पोर्टल देखें": "Explore Buyer Portal",
  "सीधा बाज़ार संपर्क और सटीक मूल्य खोज": "Direct Market Linkages & Price Discovery",
  "एआई द्वारा फसल रोग एवं गुणवत्ता जांच": "Integrated AI Crop Health Diagnosis",
  "किसान और खरीदार के बीच सीधा सौदा व चैट": "Direct Farmer ⇄ Buyer Deal Negotiation",
  "किसान लॉगिन (रमेश - मेरठ)": "Farmer Login (Ramesh - Meerut)",
  "खरीदार लॉगिन (शर्मा एग्रो ट्रेडर्स)": "Buyer Login (Sharma Agro Wholesaler)",
  "नमस्ते, रमेश 👋": "Hello, Ramesh 👋",
  "मेरठ, उत्तर प्रदेश": "Meerut, Uttar Pradesh",
  "सक्रिय किसान • सत्यापित प्रोफ़ाइल ✓": "Active Farmer • Verified Profile ✓",
  "आज का सबसे बेहतरीन बिक्री अवसर": "TODAY'S BEST SELLING OPPORTUNITY",
  "गेहूं (शरबती किस्म)": "Wheat (Gehun - Sharbati)",
  "सर्वश्रेष्ठ खरीदार: थोक खरीदार बी (शर्मा एग्रो)": "Best Buyer: Mandi/Bulk Buyer B (Sharma Agro)",
  "हाथ में शुद्ध भाव:": "Expected Net Price:",
  "(₹100 अनुमानित भाड़ा काटने के बाद)": "(After ₹100 estimated transport)",
  "सिफारिश देखें": "View Recommendation",
  "त्वरित सेवाएं": "Quick Actions",
  "मेरी फसलें": "My Crops",
  "जोड़ें व देखें": "List & Manage",
  "मंडी भाव": "Market Prices",
  "सटीक दाम": "Price Discovery",
  "खरीदार खोजें": "Find Buyers",
  "सीधा संपर्क": "Direct Linkage",
  "एआई फसल जांच": "AI Crop Scan",
  "रोग व स्वास्थ्य": "Pest & Health",
  "मौसम पूर्वानुमान": "Weather",
  "7-दिवसीय सलाह": "Agro Forecast",
  "मेरे ऑर्डर": "My Orders",
  "1 सक्रिय सौदा": "1 Active Offer",
  "एआई फसल स्वास्थ्य": "AI CROP HEALTH",
  "मंडी ले जाने से पहले फसल की बीमारी व गुणवत्ता की जांच करें": "Check your crop for diseases & pests before taking to market",
  "अंतिम जांच: गेहूं (स्वस्थ ✓)": "Last Scan: Wheat (Healthy ✓)",
  "फसल जांचें": "Scan Crop",
  "एआई स्मार्ट बिक्री सिफारिश": "SMART SELLING RECOMMENDATION",
  "आपके लिए सर्वश्रेष्ठ विकल्प": "Best Option For You",
  "यह खरीदार क्यों चुनें?": "Why this buyer?",
  "अधिक शुद्ध मुनाफा": "Higher effective price",
  "मात्रा की पूरी मांग": "Good quantity match",
  "नजदीक (15 किमी दूरी)": "Nearby (15 km away)",
  "सत्यापित खरीदार ✓": "Verified Buyer ✓",
  "शुद्ध हाथ में: ₹2,450/क्विंटल": "Net In-Hand: ₹2,450/Qtl",
  "बातचीत व मोलभाव": "Chat & Negotiate",
  "सीधा ऑफर भेजें": "Send Direct Offer",
  "मौसम कृषि परामर्श": "Agro-Weather Advisory",
  "एआई फसल रोग व स्वास्थ्य जांच": "AI Crop Health Scanner",
  "बीमारी व कीट जांच के लिए पत्ते की फोटो लें": "Upload Crop Image for Disease & Pest Scan",
  "डेमो सैंपल चुनें या फोटो खींचें:": "Select Sample Demo Image or Upload Custom:",
  "प्याज (Pyaz)": "Onion (Pyaz)",
  "गेहूं (Gehun)": "Wheat (Gehun)",
  "स्वस्थ गेहूं": "Healthy Wheat",
  "एआई फसल जांच शुरू करें": "Run AI Crop Diagnostic Scan",
  "एआई जांच परिणाम": "AI ANALYSIS RESULT",
  "फसल:": "Crop:",
  "पहचानी गई स्थिति:": "Detected Condition:",
  "गंभीरता स्तर:": "Severity Level:",
  "प्रभावित क्षेत्र:": "Affected Area:",
  "किसान के लिए कृषि सलाह:": "Farmer Recommendation:",
  "विस्तृत रिपोर्ट देखें": "View Detailed Report",
  "उपयुक्त खरीदार खोजें": "Find Suitable Buyers",
  "मंडी मूल्य खोज": "Mandi Price Discovery",
  "फसल चुनें:": "Filter by Crop:",
  "मंडी व खरीदार भाव तुलना": "Market / Buyer Comparison",
  "बोली का भाव": "Quoted Price",
  "दूरी": "Distance",
  "अनुमानित भाड़ा": "Est. Transport",
  "शुद्ध हाथ में": "Net In-Hand",
  "कार्रवाई": "Action",
  "यहाँ बेचें": "Sell Here",
  "7-दिवसीय मूल्य रुझान व एआई बाज़ार समीक्षा": "7-Day Price Trend & AI Market Insight",
  "मेरे ऑर्डर व डिलीवरी ट्रैकिंग": "My Orders & Fulfilment",
  "ऑफर भेजा": "Offer Sent",
  "खरीदार द्वारा स्वीकृत": "Accepted by Buyer",
  "रास्ते में": "In Transit",
  "पूर्ण व भुगतान प्राप्त": "Completed & Paid",
  "स्टेटस आगे बढ़ाएं (डेमो)": "Advance Status (Judge Demo)",
  "खरीदार से चैट": "Chat Buyer",
  "थोक खरीदार पोर्टल": "Buyer Portal",
  "सक्रिय मांग": "Active Requirements",
  "प्राप्त ऑफर": "Pending Offers",
  "नई फसल की मांग पोस्ट करें": "Post New Crop Requirement",
  "एआई सर्वश्रेष्ठ मिलान": "AI MATCH FOUND",
  "उपलब्ध किसान उत्पाद": "AVAILABLE FARMER PRODUCE",
  "फसल विवरण देखें": "View Produce Details",
  "रमेश से चैट करें": "Chat with Ramesh",
  "सौदा पक्का करें": "Lock Purchase Order",
  "ऑफर लॉक करें": "Lock Deal Offer",
  "सीधी बातचीत व मोलभाव": "Direct Negotiation Chat",
  "सौदा पक्का! कल सुबह माल dispatch होगा।": "Deal confirmed! Order dispatching tomorrow.",
  "और मात्रा उपलब्ध है क्या?": "Need more quantity",
  "डिलीवरी पर डायरेक्ट DBT भुगतान": "Instant DBT Payment on delivery",
  "मोलभाव के लिए संदेश लिखें...": "Type direct message to negotiate...",
  "भेजें": "Send",
  "किसान मोड": "Farmer Mode",
  "सीधी चैट": "Direct Chat",
  "होम": "Home",
  "फसलें": "Crops",
  "खरीदार": "Buyers",
  "ऑर्डर": "Orders",
  "प्रोफ़ाइल": "Profile",
  "डैशबोर्ड": "Dashboard",
  "मांग": "Requirements",
  "चैट": "Chats"
};
